### ISSUE TITLE
Feature request: Add landmarks to open files dialog

### ISSUE THREAD

**Issue by mattrussellcrick** [saalfeldlab/bigwarp#117]
Hi,

Can we get an optional field to load the landmarks in the open files dialog, please? That would help when returning to a session (especially when there's a crash of some kind). Ideally this would also include an option to apply the transformation and center the view on the first landmark.

Cheers,

Matt

**Comment by bogovicj** [comment]
Started here https://github.com/saalfeldlab/bigwarp/commit/b97d558a8241697a50a0177aee2869465dc4c48d

**Comment by bogovicj** [comment]
Thanks @mattrussellcrick !

These will be in the next release.

I'm hesitant to include this option:
> Ideally this would also include an option to ... center the view on the first landmark.

In part because it makes the first landmark "special", and it just saves you one double-click.
Very possible I'm missing some compelling reason for it - can you explain how it would be helpful to you?

**Comment by mattrussellcrick** [comment]
Thanks for that.

Centering on the first landmark is a way of dealing with the, "Where are my imagesets?" question when you first open the view windows. It's not necessary per se, but would be a way of making sure a user could see their images when they start (a particular problem with CLEM alignments, where the scales are so different) without having to remember that a double-click can take you there. Which landmark to use is kind of arbitrary so it just seemed easiest to use the first landmark. But I take your points.

It relates to another feature request I made (https://github.com/saalfeldlab/bigwarp/issues/120#issue-801535657). If that other feature is possible, I think it might negate the need for a feature of centering on the first landmark.

In general, it's quite easy to get lost in 3D space when viewing volume imagesets. So I'm trying to think of a few ways of dealing with that 😄

Cheers,
Matt

**Comment by bogovicj** [comment]
Hi @mattrussellcrick ,

You can now select landmarks from the open dialog, so I'm going to close this issue.

I've decided against "centering on the first landmark" as part of that dialog, largely because it's possible to center the view on any landmark by double-clicking in the landmark table.  I appreciate the problem though, which is why I'm leaving https://github.com/saalfeldlab/bigwarp/issues/120 open, and hope to make that better soon.

Thanks again for the suggestion!
