### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException on bigwarp.getTransformation().inverse().apply (2D)

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#92]
I think it could be related to the bug https://github.com/saalfeldlab/bigwarp/issues/91

Basically, with a 2D registration, calling `bigwarp.getTransformation().apply()` works, but `bigwarp.getTransformation().inverse().apply` returns this error:

```
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at net.imglib2.realtransform.inverse.InverseRealTransformGradientDescent.apply(InverseRealTransformGradientDescent.java:204)
	at net.imglib2.realtransform.inverse.InverseRealTransformGradientDescent.apply(InverseRealTransformGradientDescent.java:226)
	at net.imglib2.realtransform.inverse.WrappedIterativeInvertibleRealTransform.applyInverse(WrappedIterativeInvertibleRealTransform.java:85)
	at net.imglib2.realtransform.InverseRealTransform.apply(InverseRealTransform.java:85)
	at net.imglib2.realtransform.Wrapped2DTransformAs3D.apply(Wrapped2DTransformAs3D.java:37)
```

**Comment by NicoKiaru** [comment]
Hum, still there, same dependencies and commit as the other issue:

```
		<imglib2.version>5.9.0</imglib2.version>
		<imglib2-ij.version>2.0.0-beta-46</imglib2-ij.version>
		<bigdataviewer-core.version>9.0.1</bigdataviewer-core.version>
		<bigdataviewer-vistools.version>1.0.0-beta-20</bigdataviewer-vistools.version>
		<spim_data.version>2.2.4</spim_data.version>
		<ui-behaviour.version>2.0.1</ui-behaviour.version>
		<bigwarp_fiji.version>5.1.1-SNAPSHOT</bigwarp_fiji.version>
		<scijava-ui-swing.version>0.13.0</scijava-ui-swing.version>
```

**Comment by bogovicj** [comment]
thanks for checking

**Comment by bogovicj** [comment]
Can you try this as a workaround:
```
bigwarp.unwrap2d(bigwarp.getTransformation()).inverse().apply(...)
```

I need to make some API choices, because I don't like how this workaround works :(

**Comment by NicoKiaru** [comment]
Looks like I still have an issue:

```
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at net.imglib2.realtransform.inverse.InverseRealTransformGradientDescent.apply(InverseRealTransformGradientDescent.java:204)
	at net.imglib2.realtransform.inverse.InverseRealTransformGradientDescent.apply(InverseRealTransformGradientDescent.java:226)
	at net.imglib2.realtransform.inverse.WrappedIterativeInvertibleRealTransform.applyInverse(WrappedIterativeInvertibleRealTransform.java:85)
	at net.imglib2.realtransform.InverseRealTransform.apply(InverseRealTransform.java:85)
```

Sorry it's not super informative, I can try to make a minimal example when I have a bit of time

**Comment by NicoKiaru** [comment]
Do you need a minimal example ? I've reached the point where I'm stuck on this issue...

**Comment by bogovicj** [comment]
Thanks for pinging again. 
A minimal example would help a ton.  I'll have another look at this tomorrow/Friday.

**Comment by NicoKiaru** [comment]
Which branch should I use ? `bigWarp.getTransform()` is not deprecated in the master branch apparently and `bw.getTransformation()`do not exist. Am I doing something wrong ?

**Comment by bogovicj** [comment]
Thanks for checking, I had to remind myself even.

I did some work that I hoped would address this.
If you know in advance you have a 2d affine, then you can: 
  `transform = bw.affine2d()`

`bw.getTransformation()` should exist on master [check here](https://github.com/saalfeldlab/bigwarp/blob/master/src/main/java/bigwarp/BigWarp.java#L3313-L3316).  The return type is different though..

I need to document my thinking better - I'll write something on the wiki.

**Comment by NicoKiaru** [comment]
My bad, I was not on the master branch. I assumed it and I was wrong

**Comment by NicoKiaru** [comment]
Here you go : it's the last commit on the master forked branch : https://github.com/NicoKiaru/bigwarp

**Comment by bogovicj** [comment]
Perfect, thanks @NicoKiaru !

**Comment by bogovicj** [comment]
Thanks again @NicoKiaru ,

## The Exception
In short, can you pull from bigwarp master again, try running the test you gave me, and confirm that the test "works" (no exceptions thrown)?  Hopefully this will address your issues in general.

## Deprecated and new transforms give different results?
Nice find, I've spent some time on this already, but it's still puzzling me.  Figuring this out is very important and I'll get back to you soon.

## Details 
The commit above fixes something.  This should avoid the Exception when [passing a 3d array](https://github.com/saalfeldlab/bigwarp/blob/b79460d1c83e32e27a4db9ad2978adddfc6d1b47/src/test/java/bigwarp/TransformPoints2DTest.java#L82-L85).

You can also [pass a 2d array, but it takes a small extra step](https://github.com/saalfeldlab/bigwarp/blob/b79460d1c83e32e27a4db9ad2978adddfc6d1b47/src/test/java/bigwarp/TransformPoints2DTest.java#L96-L100):
```
RealPoint bwdTransformedPt2D = new RealPoint( 2 );
bigWarp.unwrap2d( bigWarp.getTransformation() )
     .inverse()
     .apply(pt2D, bwdTransformedPt2D); // uncomment to see the exception
```

The transforms that bigwarp keeps around are all 3D (because that's what bigdataviewer needs).  If you're working with 2d images, I just [wrap the 2d transform as a 3d transform ](https://github.com/saalfeldlab/bigwarp/blob/b79460d1c83e32e27a4db9ad2978adddfc6d1b47/src/main/java/net/imglib2/realtransform/Wrapped2DTransformAs3D.java).  I just made the wrapper more robust to transforms that don't behave a certain way.  

Most `N`d transforms will let you pass arrays/localizables/positionables with dimensionality greater than `N` as arguments without a problem.  However I wrote a class that iteratively estimates the inverse when a closed-form inverse doesn't exist (which is the case for thin plate splines), which evidently does not let you do this.  It should, and I'm going to fix it.  

Thanks so much for finding this issue, and getting an example for me.  Much much appreciated.

**Comment by bogovicj** [comment]
The difference in output was [due to a typo](https://github.com/saalfeldlab/bigwarp/commit/fb0087816589a19d26cd7b48ff83f7512969345d)... whew

**Comment by NicoKiaru** [comment]
That was fast! I'll test but no doubt this should work now. Thanks for the quick fix!

**Comment by NicoKiaru** [comment]
Solved, thanks!
